### ISSUE TITLE
WhatsApp comment on https://wiki.nikiv.dev/macOS/apps/contacts

### ISSUE THREAD

**Issue by dennislapchenko** [nikitavoloboev/knowledge#124]
### Question 🤔
```You need to add person to Contacts just to send someone a WhatsApp message.```

Maybe by now you know, that there is an official shorthand link like `https://wa.me/<number>` that opens the chat in whatsapp app, no need to save number in contacts! ☺️ Wasnt sure how to frame this if i did a PR so just creating an issue. This is something that could help many people in fact! 
Also, if on iOS, could do a shortcuts snippet that would format the link with a number from clipboard (also regexp to remove `\s` and `-`) and opens in Safari. Add this to homescreen and voila! ☺️

**Comment by nikitavoloboev** [comment]
That's nice, will try it out. ♥️

**Comment by dennislapchenko** [comment]
Glad it was something new ☺️ 
Here's how the shortcut looks like if needed (shame its source cant be just shared..):
![IMG_76E917FDC604-1](https://user-images.githubusercontent.com/17194644/227770011-55503c74-4f86-4d29-b8c9-8595d7ad6484.jpeg)
