### ISSUE TITLE
Write script that will crawl through all .md files and tell me which internal links are broken

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/knowledge#13]
I often change structure of my entries. Ideally the script if ran on the folder will return all internal links that turn out in error (lead to no file) so I can quickly fix them.

Would be awesome if it could do the fixing for me too by looking at the name and finding it in SUMMARY.md

**Comment by nikitavoloboev** [comment]
Can scan through all files in the repo and get all hyperlinks: `[]()` and see if the link starts with `http`. If not then it's probably an internal link and I can see if I can reach the file from that link relative to my current file.

**Comment by ctm** [comment]
Hello Nikita, I wrote [mdck](https://github.com/ctm/mdck) in the last few days to help me learn rust. If it helps you out, that's great, because I really enjoy your compendium of knowledge. If not, let me know and perhaps I can fix it.

I didn't add searching SUMMARY.md (or checking fragments, or ... anything else), because I'm just taking baby steps with Rust and I also don't know if anything I've done (e.g., choosing Rust as an implementation language) precludes mdck from being useful to you.

**Comment by nikitavoloboev** [comment]
Oh wow. This is amazing. Just ran it on the repo and got: 

```
~/Dropbox/Write/knowledge master
❯ mdck .
"./text-editors/sublime-text/sublime-text.md" at about byte 78 contains the broken link: vs-code/vs-code.md
"./text-editors/sublime-text/sublime-text.md" at about byte 112 contains the broken link: vim/vim.md
"./text-editors/sublime-text/sublime-text.md" at about byte 226 contains the broken link: ../other/wiki-workflow.md
Warning: link with fragment "email" found at about byte 145 of "./tools/email.md"
Warning: link with fragment "readme" found at about byte 247 of "./macOS/apps/typinator.md"
"./macOS/apps/typinator.md" at about byte 247 contains the broken link: typinator
"./macOS/apps/typinator.md" at about byte 540 contains the broken link: km/km.md
"./health/health.md" at about byte 543 contains the broken link: supplements.md
Warning: link with fragment "read" found at about byte 368 of "./other/2do-tasks.md"
Warning: link with fragment "learn" found at about byte 384 of "./other/2do-tasks.md"
Warning: link with fragment "watch" found at about byte 402 of "./other/2do-tasks.md"
Warning: link with fragment "git" found at about byte 99 of "./programming/git.md"
"./operating-systems/linux/linux.md" at about byte 819 contains the broken link: ../package-managers/nix/nix.md
Warning: link with fragment "contributing" found at about byte 333 of "./writing/markdown.md"
```

Will fix those now.

One feature request I'd love to see if not show `byte 99` but show line numbers.

**Comment by ctm** [comment]
Oh, and if you're curious, here are the broken links it finds:
```
"./text-editors/sublime-text/sublime-text.md" at about byte 78 contains the broken link: vs-code/vs-code.md
"./text-editors/sublime-text/sublime-text.md" at about byte 112 contains the broken link: vim/vim.md
"./text-editors/sublime-text/sublime-text.md" at about byte 226 contains the broken link: ../other/wiki-workflow.md
"./macOS/apps/typinator.md" at about byte 247 contains the broken link: typinator
"./macOS/apps/typinator.md" at about byte 540 contains the broken link: km/km.md
"./health/health.md" at about byte 543 contains the broken link: supplements.md
"./operating-systems/linux/linux.md" at about byte 819 contains the broken link: ../package-managers/nix/nix.md
```

**Comment by ctm** [comment]
Wow. You're quick. Line numbers, OK. I'll take a poke at that, soon.

**Comment by nikitavoloboev** [comment]
I fixed the errors and have these left:

```
~/Dropbox/Write/knowledge master*
❯ mdck .
Warning: link with fragment "email" found at about byte 145 of "./tools/email.md"
Warning: link with fragment "read" found at about byte 368 of "./other/2do-tasks.md"
Warning: link with fragment "learn" found at about byte 384 of "./other/2do-tasks.md"
Warning: link with fragment "watch" found at about byte 402 of "./other/2do-tasks.md"
Warning: link with fragment "git" found at about byte 99 of "./programming/git.md"
Warning: link with fragment "contributing" found at about byte 333 of "./writing/markdown.md"
```

What do I do with these? What's fragments?

**Comment by ctm** [comment]
Those are warnings that are telling you that mdck hasn't checked the portion after the # in a destination. It seemed like a good idea at the time, but clearly it's annoying chatter. So I'll get rid of those warnings in the same release that uses line numbers.

**Comment by johnletey** [comment]
@nikitavoloboev I know that this is closed, but I came across another tool that does this and thought I'd share it: [liche](https://github.com/raviqqe/liche)
