### ISSUE TITLE
Can't see updates post August 13

### ISSUE THREAD

**Issue by RayyanNafees** [nikitavoloboev/knowledge#140]
# Have u stopped putting updates post 13 Aug ?

**Comment by nikitavoloboev** [comment]
Yes, building wiki stopped working as wiki got too large and vitepress could not support it.

I plan to move wiki to https://github.com/learn-anything/learn-anything.xyz soon

**Comment by RayyanNafees** [comment]
can't the project be migrated to Astro Starlight or mdpress or smth without having to move?

**Comment by nikitavoloboev** [comment]
Potentially but I don't have time currently for such migration.

**Comment by RayyanNafees** [comment]
I can do it for the knowledge u share...
I'll create the setup for u in astro
So u may generate

Just if u share me the css & js files...
With the format of your frontmatter
And one md file for example

**Comment by nikitavoloboev** [comment]
All the source code is in the repo. CSS/JS were provided by vitepress default theme. Front matter is available in the files themselves.

**Comment by nikitavoloboev** [comment]
It's okay though, I will make the migration within a month myself.

**Comment by RayyanNafees** [comment]
@nikitavoloboev any progress after 5 months :eyes:

**Comment by nikitavoloboev** [comment]
still super busy with making learn anything work, should be released within a week or so though, then journal will move there and be updated 🙏

**Comment by RayyanNafees** [comment]
U need some assistance so... your work load could be minimized  ? 👀

**Comment by RayyanNafees** [comment]
why closed the issue without any.. response ?

**Comment by nikitavoloboev** [comment]
Also building out https://solbond.co

If you want to help out, I see you work on some nice tech that we also use, reach me out on [Telegram](http://t.me/nikivi). 🖤
