### ISSUE TITLE
Automate commit messages showing what folders were changed

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/knowledge#20]
Separate multiple folders with comma.

i.e. 

`life, research: update`

**Comment by lyz-code** [comment]
Hi @nikitavoloboev, if you ever switch to MkDocs, you may like [mkdocs-newsletter](https://lyz-code.github.io/mkdocs-newsletter/) to keep your readers updated on the site changes, it is a little bit more complex on what you plan to do with this issue, but the results are worth the effort :)
