### ISSUE TITLE
Write script to download all Imgur images included in a wiki

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/knowledge#25]
In case Imgur ever closes down their hosted service, it will be a sad day.

The script should simply go through all markdown files, go to all Imgur linked images and download them to a folder.

**Comment by johnletey** [comment]
I definitely think your [markdown-parser](https://github.com/nikitavoloboev/markdown-parser) will come in very handy here!

**Comment by nikitavoloboev** [comment]
I just need to extend it to do it. I want to close this issue https://github.com/nikitavoloboev/alfred-learn-anything/issues/9 and that requires extending markdown-parser too.

**Comment by johnletey** [comment]
I see ... I can try to help out with it if you want ... does the extending have to do with nikitavoloboev/markdown-parser#10?

**Comment by nikitavoloboev** [comment]
> I can try to help out with it if you want

Would be amazing 🧡


> does the extending have to do with [nikitavoloboev/markdown-parser#10](https://github.com/nikitavoloboev/markdown-parser/issues/10)

Yes it does.
