### ISSUE TITLE
Find all markdown files that are not referenced in SUMMARY.md

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/knowledge#29]
Need to write a tool for it. So I can clean these files up or link to them if needed.

**Comment by yedhrab** [comment]
You can use my own script to create `SUMMARY.md` file automatically
https://github.com/yedhrab/YGitBookEntegration

**Comment by nikitavoloboev** [comment]
Thanks. I just need to run a check if all files are covered. As I need to impose my own structure on ordering of files.
