### ISSUE TITLE
Alphabetize/group the categories

### ISSUE THREAD

**Issue by brandonros** [nikitavoloboev/knowledge#31]

**Comment by nikitavoloboev** [comment]
I prefer it the way it is now.

**Comment by brandonros** [comment]
It makes finding things hard/random...

**Comment by nikitavoloboev** [comment]
It's just I want to keep certain things on the top like `Sharing`, `Meta` and `Ideas` and I want to keep `Looking back` last.

I'll consider alphabetizing the rest.
