### ISSUE TITLE
Ability to give suggestions on pages? Two Book suggestions.

### ISSUE THREAD

**Issue by waynehoover** [nikitavoloboev/knowledge#32]
Heya.

First awesome idea, it has inspired me to want to start something like this. One thing I noticed though is that it might be nice to have a place for suggestions, or maybe that is what these github issues could be. Anyways, here is my suggestion:

I see you read "Rich dad poor dad" and while I think it's a good beginner book on the subject I didn't find a lot of actionable advice in the book. If you really want to read a book with 10x, may I say even 100x more power to change your life in I would suggest: "The millionaire fastlane" that book changed my life.

If you want some more gold check out the amazing community that has sprung up around this too https://www.thefastlaneforum.com/community/ 

He also released a v2 I would call it of millionaire fastlane called "Unscripted" that also is full of gold. His first book in audio format is amazing though if I had to choose.

Thanks again for sharing all you do, it's very inspiring. It reminds me of a section in the epic book Conversations with God (another must read) where God says that the ALL the worlds problems would melt away in 90 days if everyone was transparent about everything with everyone.

**Comment by nikitavoloboev** [comment]
Thanks. I'll check them out. :)

**Comment by nikitavoloboev** [comment]
Although [this comment](https://www.reddit.com/r/Entrepreneur/comments/7s8kaw/the_millionaire_fastlane_framework_works/) is rather negative to it.
