### ISSUE TITLE
tag management PixaveApp

### ISSUE THREAD

**Issue by mojopreneur** [nikitavoloboev/knowledge#33]
I find editing tags on PixaveApp tedious using their editor. Can you edit tags more directly?
Thanks!

**Comment by nikitavoloboev** [comment]
What do you mean more directly? You can make KM macro to autofill the tag when you hover over an image.

**Comment by mojopreneur** [comment]
Thanks for your fast response.

I'm not sure what you're referring to re "autofill the tag" or KM macros. When I put my cursor over an image nothing happens. I can bring up a lot of options with a right click but I see no macro or automated options. I'm working on a Mac btw.

I have thousands of images and thousands of tags. About one-third of the tags are close duplicates such as Jack o Lantern and Jack o' Lantern and jack o lantern. I'd like to cut down on all the tags and  whenever possible consolidate these near duplicates. Bringing up the tag list and editing them one by one (sometimes I can delete a group of tags) takes a long time.

Thank you,
Judy

**Comment by nikitavoloboev** [comment]
I don't really use tags much in Pixave so can't help you. 😞
